const fse = require('fs-extra');

const paths = [
  ['static/text', 'default'],
  ['static/text', 'disabled'],
  ['static/text', 'required'],
  ['static/text', 'placeholder'],
  ['static/text', 'value'],
  ['static/text', 'min-max'],
  ['static/text', 'hint'],
  ['static/text', 'validation'],
  ['static/text', 'pattern'],
  ['static/number', 'default'],
  ['static/number', 'disabled'],
  ['static/number', 'required'],
  ['static/number', 'placeholder'],
  ['static/number', 'value'],
  ['static/number', 'min-max'],
  ['static/number', 'step'],
  ['static/number', 'hint'],
  ['static/number', 'validation'],
  ['static/textarea', 'default'],
  ['static/textarea', 'disabled'],
  ['static/textarea', 'required'],
  ['static/textarea', 'placeholder'],
  ['static/textarea', 'value'],
  ['static/textarea', 'min-max'],
  ['static/textarea', 'hint'],
  ['static/textarea', 'validation'],
  ['static/textarea', 'pattern'],
  ['static/select', 'default'],
  ['static/select', 'disabled'],
  ['static/select', 'required'],
  ['static/select', 'groups'],
  ['static/select', 'multi'],
  ['static/select', 'option'],
  ['static/select', 'value'],
  ['static/select', 'placeholder'],
  ['static/select', 'hint'],
  ['static/select', 'validation'],
  ['static/autocomplete', 'default'],
  ['static/autocomplete', 'disabled'],
  ['static/autocomplete', 'required'],
  ['static/autocomplete', 'groups'],
  ['static/autocomplete', 'multi'],
  ['static/autocomplete', 'option'],
  ['static/autocomplete', 'value'],
  ['static/autocomplete', 'placeholder'],
  ['static/autocomplete', 'hint'],
  ['static/autocomplete', 'validation'],
  ['static/datepicker', 'default'],
  ['static/datepicker', 'disabled'],
  ['static/datepicker', 'required'],
  ['static/datepicker', 'value'],
  ['static/datepicker', 'range'],
  ['static/slider', 'default'],
  ['static/slider', 'disabled'],
  ['static/slider', 'required'],
  ['static/slider', 'value'],
  ['static/slider', 'range'],
  ['static/slider', 'tooltip'],
  ['static/slider', 'ticks'],
  ['static/slider', 'min-max'],
  ['static/slider', 'step'],
  ['static/switch', 'default'],
  ['static/switch', 'disabled'],
  ['static/switch', 'required'],
  ['static/switch', 'value'],
  ['static/checkbox', 'default'],
  ['static/checkbox', 'disabled'],
  ['static/checkbox', 'required'],
  ['static/checkbox', 'value'],
  ['static/radio', 'default'],
  ['static/radio', 'inline'],
  ['static/radio', 'disabled'],
  ['static/radio', 'required'],
  ['static/radio', 'option'],
  ['static/radio', 'value'],
  ['dynamic/select', 'default'],
  ['dynamic/select', 'multi'],
  ['dynamic/select', 'value'],
  ['dynamic/select', 'value-multi'],
  ['dynamic/select', 'clean'],
  ['dynamic/autocomplete', 'default'],
  ['dynamic/autocomplete', 'multi'],
  ['dynamic/autocomplete', 'value'],
  ['dynamic/autocomplete', 'value-multi'],
  ['dynamic/autocomplete', 'clean'],
  ['dynamic/switch', 'default'],
  ['dynamic/switch', 'value'],
  ['dynamic/switch', 'clean'],
  ['dynamic/checkbox', 'default'],
  ['dynamic/checkbox', 'value'],
  ['dynamic/checkbox', 'clean'],
  ['dynamic/radio', 'default'],
  ['dynamic/radio', 'value'],
  ['dynamic/radio', 'clean'],
  ['dynamic/radio', 'clean'],
  ['custom', 'fruits'],
  ['custom', 'second'],
  ['custom', 'group'],
];

// To copy a folder or file, select overwrite accordingly
try {
  paths.forEach((files) => {
    fse.copySync(
      `src/app/components/${files[0]}/${files[1]}/${files[1]}.component.html`,
      `src/assets/files/${files[0]}/${files[1]}.txt`,
      { overwrite: true }
    );
  });

  console.log('success!');
} catch (err) {
  console.error(err);
}
